### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by ghost** [netgroup-polito/netbee#1]
@name29   While compiling netbee on my Ubuntu system, with all dependencies installed (followed the wiki guide throughly), I get an error while making the source:

While running the cmake command
```
# cd netbee/src
# cmake .
# make
```

I get the following error:

```
home/pradeep/netbee/src/nbpflcompiler/hashtable.h:229:53: error: no matching function for call to ‘make_pair(std::__cxx11::basic_string<char>&, PFLBasicBlock*&)’
   result = m_HashTable.insert(make_pair<TKey, TItem>(key, item));
```
```
nbpflcompiler/CMakeFiles/nbpflcompiler.dir/build.make:194: recipe for target 'nbpflcompiler/CMakeFiles/nbpflcompiler.dir/pflcfg.cpp.o' failed
make[2]: *** [nbpflcompiler/CMakeFiles/nbpflcompiler.dir/pflcfg.cpp.o] Error 1
CMakeFiles/Makefile2:373: recipe for target 'nbpflcompiler/CMakeFiles/nbpflcompiler.dir/all' failed
make[1]: *** [nbpflcompiler/CMakeFiles/nbpflcompiler.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```
any suggestion on what I could be doing wrong?

Thanks

**Comment by ghost** [comment]
my end goal is to use the CpQd switch with ONOS for implementing meter tables and QoS

**Comment by frisso** [comment]
Which version of Ubuntu? @ivanocerrato : which version are you using?

**Comment by ghost** [comment]
@frisso  Ubuntu 17.04, kernel 4.10 on a Oracle VirtualBox VM
gcc and g++ 6.3.0, cmake 3.7.2

**Comment by pchaigno** [comment]
For anyone looking into this in the future: it looks like this is an issue with gcc 6.3.0. A workaround is to use a lower version, such as gcc 4.8.4, which worked for me.

**Comment by frisso** [comment]
Thanks, Paul.

**Comment by stavallo** [comment]
Build also failed for me. I think the culprit is that newer compilers enable c++11 by default. I managed to build netbee with gcc 7.2.1. If interested, I can share the diff.

**Comment by pchaigno** [comment]
@stavallo A pull request maybe? 😃

**Comment by stavallo** [comment]
[0001-Switch-to-C-11.txt](https://github.com/netgroup-polito/netbee/files/1636182/0001-Switch-to-C-11.txt)
I was too lazy to create a pull request. Please find attached a git commit to push on top of the upstream master. I was able to build netbee with both g++ 4.9.4 and 7.2.1.

**Comment by ivanocerrato** [comment]
I have applied the patch. @stavallo thanks.
